### ISSUE TITLE
Dead Project?

### ISSUE THREAD

**Issue by iamenderst** [YamlEngineer/DevOps.nvim#1]
New to NvChad and found this project.
Fresh NvChad install and after I mv DevOps.nvim ~/.config/nvim/lua/custom and run nvim +PackerSync I get Not an editor command: PackerSync. Must have been a lot of changes to NvChad since this project was last updated.

**Comment by ByteHolic** [comment]
> New to NvChad and found this project.
> Fresh NvChad install and after I mv DevOps.nvim ~/.config/nvim/lua/custom and run nvim +PackerSync I get Not an editor command: PackerSync. Must have been a lot of changes to NvChad since this project was last updated.
> 

I updated the configs with the new version of nvchad and now you can use it
